version: "3.8"

services:
  #Это конфигурация Docker Compose для запуска музыкального бота Discord.
  discord-music:
    container_name: discord-music
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    env_file: music.env
    image: eritislami/evobot:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "false"

networks:
  default:
    external: true
    name: $NETWORK
